"""Add warehouse models

Revision ID: 2c067a71132b
Revises: a9e97a6ea1dc
Create Date: 2026-01-19 17:29:48.569153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c067a71132b'
down_revision = 'a9e97a6ea1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default_intake', sa.Boolean(), nullable=True),
    sa.Column('is_shipping_location', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='unique_product_warehouse')
    )
    op.create_table('stock_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('length_mm',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('width_mm',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('thickness_mm',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('stock_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'warehouse', ['warehouse_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('stock_intake', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('thickness_mm',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('width_mm',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('length_mm',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)

    op.drop_table('stock_transfer')
    op.drop_table('product_stock')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
