"""Add timeline events table

Revision ID: 797a16420d59
Revises: 4bc48ecc8a7c
Create Date: 2025-10-01 12:07:03.390603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797a16420d59'
down_revision = '4bc48ecc8a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_event')
    # ### end Alembic commands ###
