"""make selling_price nullable

Revision ID: a3942e0d429a
Revises: 797a16420d59
Create Date: 2025-11-30 16:16:37.833144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3942e0d429a'
down_revision = '797a16420d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('selling_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('selling_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
