"""Add address field to Customer model

Revision ID: a9e97a6ea1dc
Revises: 62a62c53d14a
Create Date: 2025-12-15 00:59:53.003494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e97a6ea1dc'
down_revision = '62a62c53d14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_variant', schema=None) as batch_op:
        batch_op.drop_column('sunroof_width_in')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('stock_intake_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_intake_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('car_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunroof_width_in', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
